[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
# Clean mode variables (prevents cache/logs folders in production)
PYTHONDONTWRITEBYTECODE = "1"
DISABLE_FILE_LOGGING = "true" 
PYTHONUNBUFFERED = "1"
PORT = "8000"

# Other environment variables should be set via Railway dashboard for security
# BOT_TOKEN, API keys, etc.